INSERT INTO TIEMPO (
    ANIO
) SELECT DISTINCT TEMPORAL.YEAR
FROM TEMPORAL;

INSERT INTO LUGAR (
    PAIS
) SELECT DISTINCT TEMPORAL.COUNTRY
FROM TEMPORAL;

INSERT INTO TOTALES (
    TOTAL_DAMAGE,
    TOTAL_DEATHS,
    TOTAL_HOUSES_DESTROYED,
    TOTAL_HOUSES_DAMAGED
) SELECT 
    TEMPORAL.TOTAL_DAMAGE,
    TEMPORAL.TOTAL_DEATHS,
    TEMPORAL.TOTAL_HOUSES_DESTROYED,
    TEMPORAL.TOTAL_HOUSES_DAMAGED
FROM TEMPORAL;

INSERT INTO LONGITUD (
    MAXIMUM_WATER_HEIGHT
) SELECT TEMPORAL.MAXIMUM_WATER_HEIGHT
FROM TEMPORAL;

INSERT INTO TSUNAMI (
    TSUNAMI_EVENT_VALIDITY
) SELECT TEMPORAL.TSUNAMI_EVENT_VALIDITY
FROM TEMPORAL;