
INSERT INTO TIEMPO (
    ANIO
) SELECT DISTINCT TEMPORAL.YEAR
FROM TEMPORAL;

INSERT INTO LUGAR (
    PAIS
) SELECT DISTINCT TEMPORAL.COUNTRY
FROM TEMPORAL;

INSERT INTO LONGITUD (MAXIMUM_WATER_HEIGHT)
SELECT DISTINCT TEMPORAL.MAXIMUM_WATER_HEIGHT
FROM TEMPORAL;

INSERT INTO HISTORIAL_TSUNAMIS (
    ID_TIEMPO,
    ID_LUGAR,
    ID_LONGITUD,
    TOTAL_DAMAGE,
    TOTAL_DEATHS,
    TOTAL_HOUSES_DESTROYED,
    TOTAL_HOUSES_DAMAGED
) SELECT 
    (SELECT ID_TIEMPO FROM TIEMPO WHERE ANIO = TEMPORAL.YEAR),
    (SELECT ID_LUGAR FROM LUGAR WHERE PAIS = TEMPORAL.COUNTRY),
    (SELECT ID_LONGITUD FROM LONGITUD WHERE MAXIMUM_WATER_HEIGHT = TEMPORAL.MAXIMUM_WATER_HEIGHT),
    ISNULL(TEMPORAL.TOTAL_DAMAGE,0.00),
    ISNULL(TEMPORAL.TOTAL_DEATHS,0),
    ISNULL(TEMPORAL.TOTAL_HOUSES_DESTROYED,0),
    ISNULL(TEMPORAL.TOTAL_HOUSES_DAMAGED,0)
FROM TEMPORAL;
