
CREATE TABLE TIEMPO(
    ID_TIEMPO INT PRIMARY KEY IDENTITY(1,1),
    ANIO INT DEFAULT 0
);

CREATE TABLE LUGAR(
    ID_LUGAR INT PRIMARY KEY IDENTITY(1,1),
    PAIS VARCHAR(75) DEFAULT ''
);

CREATE TABLE LONGITUD(
    ID_LONGITUD INT PRIMARY KEY IDENTITY(1,1),
    MAXIMUM_WATER_HEIGHT DECIMAL(10,2) DEFAULT 0.00
);

CREATE TABLE HISTORIAL_TSUNAMIS(
    ID_HISTORIAL_TSUNAMIS INT PRIMARY KEY IDENTITY(1,1),
    ID_TIEMPO INT,
    ID_LUGAR INT,
    ID_LONGITUD INT,
    TOTAL_DAMAGE DECIMAL DEFAULT 0.00,
    TOTAL_DEATHS INT DEFAULT 0,
    TOTAL_HOUSES_DESTROYED INT DEFAULT 0,
    TOTAL_HOUSES_DAMAGED INT DEFAULT 0,
    FOREIGN KEY (ID_TIEMPO) REFERENCES TIEMPO(ID_TIEMPO),
    FOREIGN KEY (ID_LUGAR) REFERENCES LUGAR(ID_LUGAR),
    FOREIGN KEY (ID_LONGITUD) REFERENCES LONGITUD(ID_LONGITUD)
);