CREATE DATABASE practica1ss2;

CREATE TABLE practica1ss2.TEMPORAL(
	YEAR VARCHAR(50),
	MONTH VARCHAR(50),
	DAY VARCHAR(50),
	HOUR VARCHAR(50),
	MINUTE VARCHAR(50),
	SECOND VARCHAR(50),
	TSUNAMI_EVENT_VALIDITY VARCHAR(50),
	TSUNAMI_CAUSE_CODE VARCHAR(50),
	EARTHQUACKE_MAGNITUDE VARCHAR(50),
	DEPOSITS VARCHAR(50),
	LATITUDE VARCHAR(50),
	LONGITUDE VARCHAR(50),
	MAXIMUM_WATER_HEIGHT VARCHAR(50),
	NUMBER_OF_RUNUPS VARCHAR(50),
	TSUNAMI_MAGNITUDE VARCHAR(50),
	TSUNAMI_INTENSITY VARCHAR(50),
	TOTAL_DEATHS VARCHAR(50),
	TOTAL_MISSING VARCHAR(50),
	TOTAL_MISSING_DESCRIPTION VARCHAR(50),
	TOTAL_INJURIES VARCHAR(50),
	TOTAL_DAMAGE VARCHAR(50),
	TOTAL_DAMAGE_DESCRIPTION VARCHAR(50),
	TOTAL_HOUSES_DESTROYED VARCHAR(50),
	TOTAL_HOUSES_DAMAGED VARCHAR(50),
	COUNTRY VARCHAR(100),
	LOCATION_NAME VARCHAR(100)
);

BULK INSERT 
	practica1ss2.TEMPORAL
FROM
	'C:\Users\rodri\Downloads\historial_tsumamis.csv'
With(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2
);
