SELECT L.PAIS AS 'Pais', AVG(O.MAXIMUM_WATER_HEIGHT) AS 'Total Damage'
FROM LUGAR L
JOIN HISTORIAL_TSUNAMIS HT ON HT.ID_LUGAR = L.ID_LUGAR
JOIN LONGITUD O ON HT.ID_LONGITUD = O.ID_LONGITUD
WHERE O.MAXIMUM_WATER_HEIGHT <> 0.00
GROUP BY L.PAIS
ORDER BY L.PAIS;